### ISSUE TITLE
java.lang.AssertionError

### ISSUE THREAD

**Issue by po1xi548Rysh8BH6** [YannCebron/m68kplugin#56]
### Steps to Reproduce
Please provide code sample if applicable

### Runtime Information
Plugin version : 0.1.72
IDE: CLion 2023.1.3 (CL-231.9011.31)
OS: macOS 13.3.1

### Stacktrace
```
java.lang.AssertionError
	at com.yanncebron.m68kplugin.lang.M68kConditionalAssemblyCodeBlockSupportHandler.getCodeBlockMarkerRanges(M68kConditionalAssemblyCodeBlockSupportHandler.java:57)
	at com.intellij.codeInsight.highlighting.CodeBlockSupportHandler.findMarkersRanges(CodeBlockSupportHandler.java:77)
	at com.intellij.codeInsight.highlighting.CodeBlockSupportHandler.findMarkersRanges(CodeBlockSupportHandler.java:94)
	at com.intellij.codeInsight.daemon.impl.IndentsPass$IndentsCalculator.calculate(IndentsPass.java:308)
	at com.intellij.codeInsight.daemon.impl.IndentsPass.buildDescriptors(IndentsPass.java:150)
	at com.intellij.codeInsight.daemon.impl.IndentsPass.doCollectInformation(IndentsPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by YannCebron** [comment]
Thanks for report, fixed in next version.
